_units = {
    "sea_water_conservative_temperature": "degC",
    "sea_water_absolute_salinity": "g kg-1",
    "sea_water_practical_salinity": "1",
    "sea_water_potential_temperature": "degC",
    "sea_water_preformed_salinity": "g kg-1",
}

_func_standard_name = (
    # rc ("CT_from_enthalpy", "sea_water_conservative_temperature", "degC"),
    # rc ("CT_from_enthalpy_exact", "sea_water_conservative_temperature", "degC"),
    # rc ("CT_from_entropy", "sea_water_conservative_temperature", "degC"),
    # rc ("CT_from_pt", "sea_water_conservative_temperature", "degC"),
    # rc ("CT_from_rho", "sea_water_conservative_temperature", "degC"),
    # rc ("CT_from_t", "sea_water_conservative_temperature", "degC"),
    ("C_from_SP", "sea_water_electrical_conductivity", "mS cm-1"),
    ("SA_from_SP", "sea_water_absolute_salinity", "g kg-1"),
    ("SA_from_SP_Baltic", "sea_water_absolute_salinity", "g kg-1"),
    ("SA_from_Sstar", "sea_water_absolute_salinity", "g kg-1"),
    ("SA_from_rho", "sea_water_absolute_salinity", "g kg-1"),
    ("SP_from_C", "sea_water_practical_salinity", "1"),
    ("SP_from_SA", "sea_water_practical_salinity", "1"),
    ("SP_from_SA_Baltic", "sea_water_practical_salinity", "1"),
    ("SP_from_SK", "sea_water_practical_salinity", "1"),
    ("SP_from_SR", "sea_water_practical_salinity", "1"),
    ("SP_from_Sstar", "sea_water_practical_salinity", "1"),
    ("SP_salinometer", "sea_water_practical_salinity", "1"),
    ("SR_from_SP", "sea_water_reference_salinity", "g kg-1"),
    ("Sstar_from_SA", "sea_water_preformed_salinity", "g kg-1"),
    ("Sstar_from_SP", "sea_water_preformed_salinity", "g kg-1"),
    ("f", "coriolis_parameter", "s-1"),
    ("p_from_z", "sea_water_pressure", "dbar"),
    ("pt0_from_t", "sea_water_potential_temperature", "degC"),
    ("pt_from_CT", "sea_water_potential_temperature", "degC"),
    ("pt_from_entropy", "sea_water_potential_temperature", "degC"),
    # if p_ref is not 0 this next standard name is incorrect
    ("pt_from_t", "sea_water_potential_temperature", "degC"),
    ("rho", "sea_water_density", "kg m-3"),
    ("rho_t_exact", "sea_water_density", "kg m-3"),
    ("sigma0", "sea_water_sigma_t", "kg m-3"),  # only applies to pressure=0
    ("sound_speed", "speed_of_sound_in_sea_water", "m s-1"),
    ("sound_speed_t_exact", "speed_of_sound_in_sea_water", "m s-1"),
    ("t_from_CT", "sea_water_temperature", "degC"),
    # not sure how I feel about this next one
    ("z_from_p", "height_above_mean_sea_level", "m"),
)

_func_standard_name_units = (
    ("CT_first_derivatives", None, None),
    ("CT_first_derivatives_wrt_t_exact", None, None),
    ("CT_freezing", "freezing_temperature_of_sea_water", "degC"),  # Not sure
    ("CT_freezing_first_derivatives", None, None),
    ("CT_freezing_first_derivatives_poly", None, None),
    ("CT_freezing_poly", "freezing_temperature_of_sea_water", "degC"),  # Not sure
    ("CT_from_enthalpy", "sea_water_conservative_temperature", ""),
    ("CT_from_enthalpy_exact", "sea_water_conservative_temperature", ""),
    ("CT_from_entropy", "sea_water_conservative_temperature", ""),
    ("CT_from_pt", "sea_water_conservative_temperature", ""),
    ("CT_from_rho", "sea_water_conservative_temperature", ""),
    ("CT_from_t", "sea_water_conservative_temperature", ""),
    ("CT_maxdensity", None, "degC"),
    ("CT_second_derivatives", None, None),
    ("C_from_SP", "sea_water_electrical_conductivity", "mS cm-1"),
    ("Fdelta", None, "1"),
    ("Helmholtz_energy_ice", None, "J kg-1"),
    ("Hill_ratio_at_SP2", None, "1"),
    ("IPV_vs_fNsquared_ratio", None, None),
    ("Nsquared", None, None),
    ("O2sol", None, "umol kg-1"),
    ("O2sol_SP_pt", None, "umol kg-1"),
    ("SAAR", None, "1"),
    ("SA_freezing_from_CT", "sea_water_absolute_salinity", ""),  # Not sure
    ("SA_freezing_from_CT_poly", "sea_water_absolute_salinity", ""),  # Not sure
    ("SA_freezing_from_t", "sea_water_absolute_salinity", ""),  # Not sure
    ("SA_freezing_from_t_poly", "sea_water_absolute_salinity", ""),  # Not sure
    ("SA_from_SP", "sea_water_absolute_salinity", ""),
    ("SA_from_SP_Baltic", "sea_water_absolute_salinity", ""),
    ("SA_from_Sstar", "sea_water_absolute_salinity", ""),
    ("SA_from_rho", "sea_water_absolute_salinity", ""),
    ("SP_from_C", "sea_water_practical_salinity", ""),
    ("SP_from_SA", "sea_water_practical_salinity", ""),
    ("SP_from_SA_Baltic", "sea_water_practical_salinity", ""),
    ("SP_from_SK", "sea_water_practical_salinity", ""),
    ("SP_from_SR", "sea_water_practical_salinity", ""),
    ("SP_from_Sstar", "sea_water_practical_salinity", ""),
    ("SP_salinometer", "sea_water_practical_salinity", ""),
    ("SR_from_SP", "sea_water_reference_salinity", ""),
    ("Sstar_from_SA", "sea_water_preformed_salinity", ""),
    ("Sstar_from_SP", "sea_water_preformed_salinity", ""),
    ("Turner_Rsubrho", None, None),
    ("adiabatic_lapse_rate_from_CT", None, "K Pa-1"),
    ("adiabatic_lapse_rate_ice", None, "K Pa-1"),
    ("alpha", None, "K-1"),
    ("alpha_on_beta", None, "kg g-1 K-1"),
    ("alpha_wrt_t_exact", None, "K-1"),
    ("alpha_wrt_t_ice", None, "K-1"),
    ("beta", None, "kg g-1"),
    ("beta_const_t_exact", None, "kg g-1"),
    ("cabbeling", None, "K-2"),
    ("chem_potential_water_ice", None, "J kg-1"),
    ("chem_potential_water_t_exact", None, "J kg-1"),
    ("cp_ice", None, "J kg-1 K-1"),
    ("cp_t_exact", "specific_heat_capacity_of_sea_water", "J kg-1 K-1"),  # Not sure
    ("deltaSA_atlas", None, None),
    ("deltaSA_from_SP", None, None),
    ("dilution_coefficient_t_exact", None, None),
    ("distance", None, None),
    ("dynamic_enthalpy", None, None),
    ("enthalpy", None, None),
    ("enthalpy_CT_exact", None, None),
    ("enthalpy_diff", None, None),
    ("enthalpy_first_derivatives", None, None),
    ("enthalpy_first_derivatives_CT_exact", None, None),
    ("enthalpy_ice", None, None),
    ("enthalpy_second_derivatives", None, None),
    ("enthalpy_second_derivatives_CT_exact", None, None),
    ("enthalpy_t_exact", None, None),
    ("entropy_first_derivatives", None, None),
    ("entropy_from_CT", None, None),
    ("entropy_from_pt", None, None),
    ("entropy_from_t", None, None),
    ("entropy_ice", None, None),
    ("entropy_second_derivatives", None, None),
    ("f", None, None),
    ("frazil_properties", None, None),
    ("frazil_properties_potential", None, None),
    ("frazil_properties_potential_poly", None, None),
    ("frazil_ratios_adiabatic", None, None),
    ("frazil_ratios_adiabatic_poly", None, None),
    ("geo_strf_dyn_height", None, None),
    ("geostrophic_velocity", None, None),
    ("gibbs_ice_part_t", None, None),
    ("gibbs_ice_pt0", None, None),
    ("gibbs_ice_pt0_pt0", None, None),
    ("grav", None, None),
    ("ice_fraction_to_freeze_seawater", None, None),
    ("indexer", None, None),
    ("internal_energy", None, None),
    ("internal_energy_ice", None, None),
    ("kappa", None, None),
    ("kappa_const_t_ice", None, None),
    ("kappa_ice", None, None),
    ("kappa_t_exact", None, None),
    ("latentheat_evap_CT", None, None),
    ("latentheat_evap_t", None, None),
    ("latentheat_melting", None, None),
    ("match_args_return", None, None),
    ("melting_ice_SA_CT_ratio", None, None),
    ("melting_ice_SA_CT_ratio_poly", None, None),
    ("melting_ice_equilibrium_SA_CT_ratio", None, None),
    ("melting_ice_equilibrium_SA_CT_ratio_poly", None, None),
    ("melting_ice_into_seawater", None, None),
    ("melting_seaice_SA_CT_ratio", None, None),
    ("melting_seaice_SA_CT_ratio_poly", None, None),
    ("melting_seaice_equilibrium_SA_CT_ratio", None, None),
    ("melting_seaice_equilibrium_SA_CT_ratio_poly", None, None),
    ("melting_seaice_into_seawater", None, None),
    ("p_from_z", None, None),
    ("pchip_interp", None, None),
    ("pot_enthalpy_from_pt_ice", None, None),
    ("pot_enthalpy_from_pt_ice_poly", None, None),
    ("pot_enthalpy_ice_freezing", None, None),
    ("pot_enthalpy_ice_freezing_first_derivatives", None, None),
    ("pot_enthalpy_ice_freezing_first_derivatives_poly", None, None),
    ("pot_enthalpy_ice_freezing_poly", None, None),
    ("pot_rho_t_exact", None, None),
    ("pressure_coefficient_ice", None, None),
    ("pressure_freezing_CT", None, None),
    ("pt0_from_t", None, None),
    ("pt0_from_t_ice", None, None),
    ("pt_first_derivatives", None, None),
    ("pt_from_CT", None, None),
    ("pt_from_entropy", None, None),
    ("pt_from_pot_enthalpy_ice", None, None),
    ("pt_from_pot_enthalpy_ice_poly", None, None),
    ("pt_from_t", None, None),
    ("pt_from_t_ice", None, None),
    ("pt_second_derivatives", None, None),
    ("rho", None, None),
    ("rho_alpha_beta", None, None),
    ("rho_first_derivatives", None, None),
    ("rho_first_derivatives_wrt_enthalpy", None, None),
    ("rho_ice", None, None),
    ("rho_second_derivatives", None, None),
    ("rho_second_derivatives_wrt_enthalpy", None, None),
    ("rho_t_exact", None, None),
    ("seaice_fraction_to_freeze_seawater", None, None),
    ("sigma0", "sea_water_sigma_t", "kg m-3"),  # only applies to pressure=0
    ("sigma1", None, None),
    ("sigma2", None, None),
    ("sigma3", None, None),
    ("sigma4", None, None),
    ("sound_speed", None, None),
    ("sound_speed_ice", None, None),
    ("sound_speed_t_exact", None, None),
    ("specvol", None, None),
    ("specvol_alpha_beta", None, None),
    ("specvol_anom_standard", None, None),
    ("specvol_first_derivatives", None, None),
    ("specvol_first_derivatives_wrt_enthalpy", None, None),
    ("specvol_ice", None, None),
    ("specvol_second_derivatives", None, None),
    ("specvol_second_derivatives_wrt_enthalpy", None, None),
    ("specvol_t_exact", None, None),
    ("spiciness0", None, None),
    ("spiciness1", None, None),
    ("spiciness2", None, None),
    ("t90_from_t68", None, None),
    ("t_deriv_chem_potential_water_t_exact", None, None),
    ("t_freezing", None, None),
    ("t_freezing_first_derivatives", None, None),
    ("t_freezing_first_derivatives_poly", None, None),
    ("t_freezing_poly", None, None),
    ("t_from_CT", None, None),
    ("t_from_pt0_ice", None, None),
    ("thermobaric", None, None),
    ("z_from_p", None, None),
)
