_names = {
    "CT_first_derivatives": ("CT_SA", "CT_pt"),
    "CT_from_enthalpy": "CT",
    "CT_from_enthalpy_exact": "CT",
    "CT_from_entropy": "CT",
    "CT_from_pt": "CT",
    "CT_from_rho": "CT",
    "CT_from_t": "CT",
    "C_from_SP": "C",
    "SA_from_SP": "SA",
    "SA_from_SP_Baltic": "SA",
    "SA_from_Sstar": "SA",
    "SA_from_rho": "SA",
    "SP_from_C": "SP",
    "SP_from_SA": "SP",
    "SP_from_SA_Baltic": "SP",
    "SP_from_SK": "SP",
    "SP_from_SR": "SP",
    "SP_from_Sstar": "SP",
    "SP_salinometer": "SP",
    "SR_from_SP": "SR",
    "Sstar_from_SA": "Sstar",
    "Sstar_from_SP": "Sstar",
    "f": "f",
    "p_from_z": "p",
    "pt0_from_t": "pt0",
    "pt_from_CT": "pt",
    "pt_from_entropy": "pt",
    "pt_from_t": "pt",
    "rho": "rho",
    "rho_t_exact": "rho",
    "sigma0": "sigma0",
    "sound_speed": "sound_speed",
    "sound_speed_t_exact": "sound_speed",
    "t_from_CT": "temperature",
    "z_from_p": "z",
}
