name: format and lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Lint with ruff
        run: |
          uvx ruff check --output-format=github .
      - name: Test code style with ruff
        run: |
          uvx ruff format --check .
